	<input type='hidden' value="<?= $_SESSION['usuario'] ?>" class='form-control' placeholder='Username' name='username' id='username' maxlength='50' />
	<input type='hidden' value="<?= $id ?>"class='form-control' placeholder='Suscriptor_id' name='suscriptor_id' id='suscriptor_id' maxlength='10' />
	<input type='hidden' class='form-control' placeholder='Suscriptores_referencias_id' name='suscriptores_referencias_id' id='suscriptores_referencias_id' maxlength='10' />

	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_1"><div class="col-md-12"><label class="mycutelabel" for="Col_1" id='titulo_Col_1'>Col_1</label><input type='text' class="form-control" placeholder='Col_1' name='col_1' id='col_1' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_2"><div class="col-md-12"><label class="mycutelabel" for="Col_2" id='titulo_Col_2'>Col_2</label><input type='text' class="form-control" placeholder='Col_2' name='col_2' id='col_2' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_3"><div class="col-md-12"><label class="mycutelabel" for="Col_3" id='titulo_Col_3'>Col_3</label><input type='text' class="form-control" placeholder='Col_3' name='col_3' id='col_3' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_4"><div class="col-md-12"><label class="mycutelabel" for="Col_4" id='titulo_Col_4'>Col_4</label><input type='text' class="form-control" placeholder='Col_4' name='col_4' id='col_4' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_5"><div class="col-md-12"><label class="mycutelabel" for="Col_5" id='titulo_Col_5'>Col_5</label><input type='text' class="form-control" placeholder='Col_5' name='col_5' id='col_5' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_6"><div class="col-md-12"><label class="mycutelabel" for="Col_6" id='titulo_Col_6'>Col_6</label><input type='text' class="form-control" placeholder='Col_6' name='col_6' id='col_6' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_7"><div class="col-md-12"><label class="mycutelabel" for="Col_7" id='titulo_Col_7'>Col_7</label><input type='text' class="form-control" placeholder='Col_7' name='col_7' id='col_7' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_8"><div class="col-md-12"><label class="mycutelabel" for="Col_8" id='titulo_Col_8'>Col_8</label><input type='text' class="form-control" placeholder='Col_8' name='col_8' id='col_8' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_9"><div class="col-md-12"><label class="mycutelabel" for="Col_9" id='titulo_Col_9'>Col_9</label><input type='text' class="form-control" placeholder='Col_9' name='col_9' id='col_9' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_10"><div class="col-md-12"><label class="mycutelabel" for="Col_10" id='titulo_Col_10'>Col_10</label><input type='text' class="form-control" placeholder='Col_10' name='col_10' id='col_10' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_11"><div class="col-md-12"><label class="mycutelabel" for="Col_11" id='titulo_Col_11'>Col_11</label><input type='text' class="form-control" placeholder='Col_11' name='col_11' id='col_11' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_12"><div class="col-md-12"><label class="mycutelabel" for="Col_12" id='titulo_Col_12'>Col_12</label><input type='text' class="form-control" placeholder='Col_12' name='col_12' id='col_12' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_13"><div class="col-md-12"><label class="mycutelabel" for="Col_13" id='titulo_Col_13'>Col_13</label><input type='text' class="form-control" placeholder='Col_13' name='col_13' id='col_13' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_14"><div class="col-md-12"><label class="mycutelabel" for="Col_14" id='titulo_Col_14'>Col_14</label><input type='text' class="form-control" placeholder='Col_14' name='col_14' id='col_14' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_15"><div class="col-md-12"><label class="mycutelabel" for="Col_15" id='titulo_Col_15'>Col_15</label><input type='text' class="form-control" placeholder='Col_15' name='col_15' id='col_15' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_16"><div class="col-md-12"><label class="mycutelabel" for="Col_16" id='titulo_Col_16'>Col_16</label><input type='text' class="form-control" placeholder='Col_16' name='col_16' id='col_16' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_17"><div class="col-md-12"><label class="mycutelabel" for="Col_17" id='titulo_Col_17'>Col_17</label><input type='text' class="form-control" placeholder='Col_17' name='col_17' id='col_17' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_18"><div class="col-md-12"><label class="mycutelabel" for="Col_18" id='titulo_Col_18'>Col_18</label><input type='text' class="form-control" placeholder='Col_18' name='col_18' id='col_18' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_19"><div class="col-md-12"><label class="mycutelabel" for="Col_19" id='titulo_Col_19'>Col_19</label><input type='text' class="form-control" placeholder='Col_19' name='col_19' id='col_19' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_20"><div class="col-md-12"><label class="mycutelabel" for="Col_20" id='titulo_Col_20'>Col_20</label><input type='text' class="form-control" placeholder='Col_20' name='col_20' id='col_20' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_21"><div class="col-md-12"><label class="mycutelabel" for="Col_21" id='titulo_Col_21'>Col_21</label><input type='text' class="form-control" placeholder='Col_21' name='col_21' id='col_21' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_22"><div class="col-md-12"><label class="mycutelabel" for="Col_22" id='titulo_Col_22'>Col_22</label><input type='text' class="form-control" placeholder='Col_22' name='col_22' id='col_22' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_23"><div class="col-md-12"><label class="mycutelabel" for="Col_23" id='titulo_Col_23'>Col_23</label><input type='text' class="form-control" placeholder='Col_23' name='col_23' id='col_23' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_24"><div class="col-md-12"><label class="mycutelabel" for="Col_24" id='titulo_Col_24'>Col_24</label><input type='text' class="form-control" placeholder='Col_24' name='col_24' id='col_24' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_25"><div class="col-md-12"><label class="mycutelabel" for="Col_25" id='titulo_Col_25'>Col_25</label><input type='text' class="form-control" placeholder='Col_25' name='col_25' id='col_25' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_26"><div class="col-md-12"><label class="mycutelabel" for="Col_26" id='titulo_Col_26'>Col_26</label><input type='text' class="form-control" placeholder='Col_26' name='col_26' id='col_26' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_27"><div class="col-md-12"><label class="mycutelabel" for="Col_27" id='titulo_Col_27'>Col_27</label><input type='text' class="form-control" placeholder='Col_27' name='col_27' id='col_27' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_28"><div class="col-md-12"><label class="mycutelabel" for="Col_28" id='titulo_Col_28'>Col_28</label><input type='text' class="form-control" placeholder='Col_28' name='col_28' id='col_28' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_29"><div class="col-md-12"><label class="mycutelabel" for="Col_29" id='titulo_Col_29'>Col_29</label><input type='text' class="form-control" placeholder='Col_29' name='col_29' id='col_29' maxlength='' /></div></div>
				<div class="col-md-4 main_col_data" style="margin-bottom:20px;; display:none;" id="col_col_30"><div class="col-md-12"><label class="mycutelabel" for="Col_30" id='titulo_Col_30'>Col_30</label><input type='text' class="form-control" placeholder='Col_30' name='col_30' id='col_30' maxlength='' /></div></div>
			</div>
		</div>
	</div>